/*****************************************************************************
 *  SquidMach Bootstrap Syscall list                                         *
 *  Copyright (C)2009 SquidMan (Alex Marshall)       <SquidMan72@gmail.com>  *
 *****************************************************************************/

	.equ	SYSCALLS_PRINT_HEX,			1
	.equ	SYSCALLS_PRINT_TEXT,			2
	.equ	SYSCALLS_PRINT_INT,			3
	.equ	SYSCALLS_GET_HW_VERSION,		4
	.equ	SYSCALLS_GET_BOOTSTRAP_VERSION,		5

